### ISSUE TITLE
無法叫出ansel介面

### ISSUE THREAD

**Issue by FeFe-Orc** [MonsterGuo/UE5_NvidiaAnsel#1]
確定Nvidia覆蓋已關閉
顯卡版本:512.29
插件位置確定在Plugins文件夾裡
確定以Standalone Game開始遊戲
但無法叫出ansel介面 :(

**Comment by MonsterGuo** [comment]
插件目录：Plugins/Ansel 。下载好后多套了层文件夹，只要拷贝Ansel文件夹
