### ISSUE TITLE
Artifacts using 360º with Lumen in 5.3 or 5.4

### ISSUE THREAD

**Issue by AngelAvellaneda** [MonsterGuo/UE5_NvidiaAnsel#10]
Good afternoon @MonsterGuo , I'm having artifacts when I use 360º with Lumen in 5.3 or 5.4 and I don't know how to fix it. I imagine it could be fixed if I left more time between shots for the scene to finish rendering, but I can't think of how to solve it.
![Unreal Engine 5 360 2024 08 22 - 12 57 13 69](https://github.com/user-attachments/assets/33dca2da-51dc-4a51-b51b-8241dab03c8e)

**Comment by tdigirolamo** [comment]
Did you find a solution to this? I get similar artifacts and it looks like I'm missing some lumen features when rendering as well

**Comment by MonsterGuo** [comment]
Add this Value in the Blueprint.
![Snipaste_2024-12-04_15-09-56](https://github.com/user-attachments/assets/437d6c80-c1fe-4d10-bd2e-3a42d6a4a4ab)
