### ISSUE TITLE
New NVapp photo mode replacing old Ansel interface

### ISSUE THREAD

**Issue by NiukNiuk** [MonsterGuo/UE5_NvidiaAnsel#14]
Hi MonsterGuo,

Since the latest nvidia driver release (566.14), the geforce experience app has been replaced by the new NVapp.
Now when using your UE5 plugin in packaged games, the old Ansel interface is not shown anymore. It's replaced by the new NVapp "photo mode".
It lacks a lot of features compared to the old Ansel version, particularily the ability to take 360° pictures.
Is there a way to bring the old Ansel interface back? or is it gone forever now? :(

Thanks!

**Comment by MonsterGuo** [comment]
It Still Can be used.

**Comment by NiukNiuk** [comment]
The old Ansel interface can still be used yes, for now (but for how long?), when you refuse to install the nvidia app instead of GeforceExperience.
But now each time you open GFExperience you get the nvidia app setup. You can decline it, for now.
If you choose to install this new nvidia app, the new photo mode replaces the old Ansel one. And it lacks critical features like 360 screenshots (+ your engine option settings)....
So in the near future when Nvidia will decide that you can't decline the nvidia app install anymore, then the old Ansel photo mode will be gone.
That's why I was asking if there's a way to "preserve" the actual Ansel mode and its features (I'm using the 360 screenshots option a lot).

**Comment by MonsterGuo** [comment]
Hi bro. That's not a question I can give you an answer to. ansel has stopped api updates for 6 years. No one can guarantee it won't be removed. Because it is not open source, all the source code is not visible. I think you need to replace it with something that can be continually updated, rather than relying on it.

**Comment by MonsterGuo** [comment]
![Snipaste_2024-12-08_16-14-29](https://github.com/user-attachments/assets/ee0b782e-56bc-495a-b59a-75257a13313f)

**Comment by MonsterGuo** [comment]
![Uploading Snipaste_2024-12-08_16-18-07.png…]()

**Comment by MonsterGuo** [comment]
![Uploading Snipaste_2024-12-08_16-18-07.png…]()

**Comment by MonsterGuo** [comment]
![Uploading Snipaste_2024-12-08_16-18-07.png…]()

**Comment by MonsterGuo** [comment]
![Snipaste_2024-12-08_16-18-07](https://github.com/user-attachments/assets/602aec8c-8b32-4fa5-8aec-7c0f03641f89)

**Comment by NiukNiuk** [comment]
Hi, thanks for the suggestion. Unfortunately it doesn't work. I've tested on several packaged projects wich include your ansel Plugin.
Doing what you suggest still brings the new interface, but greyed out. I can see the old Ansel interface behind it but it's incomplete (no 360 screenshot for example) and the mouse cursor doesn't work.

**Comment by MonsterGuo** [comment]
https://youtu.be/IwXxSSHsixY?si=BNyF9m_FyoluL4ka
