### ISSUE TITLE
UE 5.1: packaged games don't run when the plugin is activated.

### ISSUE THREAD

**Issue by NiukNiuk** [MonsterGuo/UE5_NvidiaAnsel#3]
When using the newest 5.1 version of the plugin in UE 5.1, the packaged games don't run.
Disabling the plugin and repackaging the game fixes the issue.

**Comment by MonsterGuo** [comment]
your can build a program by c++. More:https://youtu.be/IwXxSSHsixY

**Comment by NiukNiuk** [comment]
Thanks for your reply, I'll do that. Thanks again for your plugin!
