### ISSUE TITLE
UE 5.3 version?

### ISSUE THREAD

**Issue by NiukNiuk** [MonsterGuo/UE5_NvidiaAnsel#7]
Hi, are there any plans for an UE 5.3 version?
Thanks for your great work!

**Comment by farshid-emperia** [comment]
i am not admin but I have 5.3
https://1drv.ms/u/s!Ame-7WxMmLlfpxHVv4_fA-JZM8bY?e=irYDcu

**Comment by NiukNiuk** [comment]
> i am not admin but I have 5.3 https://1drv.ms/u/s!Ame-7WxMmLlfpxHVv4_fA-JZM8bY?e=irYDcu

Thanks a lot!
I've just tested it on a  packaged new basic 5.3.1 project and it seems to work fine, thanks again!!

**Comment by MonsterGuo** [comment]
@farshid-emperia  thanks a lot!👍👍👍

**Comment by MonsterGuo** [comment]
@NiukNiuk Panoramic 360 is work fine?

**Comment by NiukNiuk** [comment]
> @NiukNiuk Panoramic 360 is work fine?

Well I had to disable auto exposure or everything was white when capturing in 360.

Also some options are missing. In your 5.2 release there is "lumen high quality" etc, here there's only "high quality"
And I also had some visual bugs when capturing in 8k 360 (see picture included)
It seems like it's an old version
![TestAnsel-Win64-Shipping 360 2023 09 30 - 11 11 58 56](https://github.com/MonsterGuo/UE5_NvidiaAnsel/assets/55076309/dc0b0b67-8578-46e6-a25e-7ab62648eab2)

**Comment by MonsterGuo** [comment]
have been update!
