### ISSUE TITLE
Support for HDR

### ISSUE THREAD

**Issue by S-ed** [MonsterGuo/UE5_NvidiaAnsel#8]
Hello.
First of all. Thank you for supporting this plugin.

I've tried it and seems like HDR does not work now. It is always a black image in the output except if you switch to some debug view like F2, F5.
I've tried to change Exposure etc. Didn't work. Maybe there is a way?

**Comment by S-ed** [comment]
My bad. It does work! But You need to enable HDR on Windows settings.

**Comment by S-ed** [comment]
My bad. It does work! But You need to enable HDR on Windows settings.

**Comment by MonsterGuo** [comment]
good job！
